name: Update Progress Bar

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC

jobs:
  update-progress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update Progress in README
        run: |
          PROGRESS=$(cat progress.txt)  # Read current progress from a file
          sed -i "s#https://progress-bar.dev/[0-9]*/#https://progress-bar.dev/${PROGRESS}/#" README.md

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Updated learning progress"
          git push
